before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: .
    binary: seanime
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64

checksum:
  name_template: 'checksums.txt'

archives:
  - id: sea-archive
    name_template: '{{- .ProjectName }}-
        {{- .Version }}_
        {{- if eq .Os "darwin" }}MacOS
        {{- else }}{{- title .Os }}{{ end }}_
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}
        {{- if .Arm }}v{{ .Arm }}{{ end -}}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

release:
  github:
    owner: 5rahim
    name: seanime

  draft: true

  replace_existing_draft: true

  name_template: "v{{.Version}}"
  header: |
    ## What's new?

  footer: |
    ---
    [Open an issue](https://github.com/5rahim/seanime/issues/new/choose)
    Compare: https://github.com/5rahim/seanime/compare/{{ .PreviousTag }}...{{ .Tag }}
