before:
  hooks:
    - go mod tidy

builds:
  #  - id: seanime-darwin-amd64
  #    binary: seanime
  #    main: .
  #    goarch:
  #      - amd64
  #    goos:
  #      - darwin
  #    env:
  #      - CGO_ENABLED=1
  #      - CC=clang
  #    flags:
  #      - -trimpath
  #    ldflags:
  #      - -s -w
  #
  #  - id: seanime-darwin-arm64
  #    binary: seanime
  #    main: .
  #    goarch:
  #      - arm64
  #    goos:
  #      - darwin
  #    env:
  #      - CGO_ENABLED=1
  #      - CC=clang
  #    flags:
  #      - -trimpath
  #    ldflags:
  #      - -s -w

  - id: seanime-darwin-amd64
    binary: seanime
    main: .
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CGO_ENABLED=0

  - id: seanime-darwin-arm64
    binary: seanime
    main: .
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CGO_ENABLED=0

  - id: seanime-linux-amd64
    binary: seanime
    main: .
    goarch:
      - amd64
    goos:
      - linux
    env:
      - CGO_ENABLED=0

  - id: seanime-linux-arm64
    binary: seanime
    main: .
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CGO_ENABLED=0

  - id: seanime-windows-amd64
    binary: seanime
    main: .
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    flags:
      - -trimpath
      - -buildmode=exe
    ldflags:
      - -s -w -H=windowsgui

archives:
  - id: seanime
    name_template: '{{- .ProjectName }}-
        {{- .Version }}_
        {{- if eq .Os "darwin" }}MacOS
        {{- else }}{{- title .Os }}{{ end }}_
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}
        {{- if .Arm }}v{{ .Arm }}{{ end -}}'
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - LICENSE

release:
  github:
    owner: 5rahim
    name: seanime

  draft: true

  replace_existing_draft: true

  name_template: "v{{.Version}}"
  header: |
    ## What's new?

  footer: |
    ---
    [Open an issue](https://github.com/5rahim/seanime/issues/new/choose)
    Compare: https://github.com/5rahim/seanime/compare/{{ .PreviousTag }}...{{ .Tag }}
