# ========================================================
# Docker Compose for Seanime
# --------------------------------------------------------
# Instructions:
# 1. Uncomment ONE of the services below (cpu or nvidia).
# 2. Run 'docker-compose up -d'.
# ========================================================

services:
  # --- Option 1: Default CPU-only instance (should work on any system) ---
  seanime:
    image: ghcr.io/5rahim/seanime:latest
    container_name: seanime
    restart: unless-stopped
    ports:
      - "43211:43211"
    environment:
      - SEANIME_SERVER_HOST=0.0.0.0
      - SEANIME_DATA_DIR=/data
    volumes:
      - ./seanime-data:/data

  # --- Option 2: NVIDIA GPU instance (for NVENC hardware transcoding) ---
  # seanime-nvidia:
  #   image: ghcr.io/5rahim/seanime:latest-nvidia # Note the '-nvidia' tag
  #   container_name: seanime-nvidia
  #   restart: unless-stopped
  #   ports:
  #     - "43211:43211"
  #   environment:
  #     - SEANIME_SERVER_HOST=0.0.0.0
  #     - SEANIME_DATA_DIR=/data
  #   volumes:
  #     - ./seanime-data:/data
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]