// Code generated by 'yaegi extract github.com/5rahim/hibike/pkg/extension/onlinestream'. DO NOT EDIT.

package yaegi_interp

import (
	"github.com/5rahim/hibike/pkg/extension/onlinestream"
	"reflect"
)

func init() {
	Symbols["github.com/5rahim/hibike/pkg/extension/onlinestream/onlinestream"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dub":             reflect.ValueOf(onlinestream.Dub),
		"Sub":             reflect.ValueOf(onlinestream.Sub),
		"SubAndDub":       reflect.ValueOf(onlinestream.SubAndDub),
		"VideoSourceM3U8": reflect.ValueOf(onlinestream.VideoSourceM3U8),
		"VideoSourceMP4":  reflect.ValueOf(onlinestream.VideoSourceMP4),

		// type definitions
		"EpisodeDetails":  reflect.ValueOf((*onlinestream.EpisodeDetails)(nil)),
		"EpisodeServer":   reflect.ValueOf((*onlinestream.EpisodeServer)(nil)),
		"Provider":        reflect.ValueOf((*onlinestream.Provider)(nil)),
		"SearchOptions":   reflect.ValueOf((*onlinestream.SearchOptions)(nil)),
		"SearchResult":    reflect.ValueOf((*onlinestream.SearchResult)(nil)),
		"Settings":        reflect.ValueOf((*onlinestream.Settings)(nil)),
		"SubOrDub":        reflect.ValueOf((*onlinestream.SubOrDub)(nil)),
		"VideoExtractor":  reflect.ValueOf((*onlinestream.VideoExtractor)(nil)),
		"VideoSource":     reflect.ValueOf((*onlinestream.VideoSource)(nil)),
		"VideoSourceType": reflect.ValueOf((*onlinestream.VideoSourceType)(nil)),
		"VideoSubtitle":   reflect.ValueOf((*onlinestream.VideoSubtitle)(nil)),

		// interface wrapper definitions
		"_Provider":       reflect.ValueOf((*_github_com_5rahim_hibike_pkg_extension_onlinestream_Provider)(nil)),
		"_VideoExtractor": reflect.ValueOf((*_github_com_5rahim_hibike_pkg_extension_onlinestream_VideoExtractor)(nil)),
	}
}

// _github_com_5rahim_hibike_pkg_extension_onlinestream_Provider is an interface wrapper for Provider type
type _github_com_5rahim_hibike_pkg_extension_onlinestream_Provider struct {
	IValue             interface{}
	WFindEpisodeServer func(episode *onlinestream.EpisodeDetails, server string) (*onlinestream.EpisodeServer, error)
	WFindEpisodes      func(id string) ([]*onlinestream.EpisodeDetails, error)
	WGetSettings       func() onlinestream.Settings
	WSearch            func(opts onlinestream.SearchOptions) ([]*onlinestream.SearchResult, error)
}

func (W _github_com_5rahim_hibike_pkg_extension_onlinestream_Provider) FindEpisodeServer(episode *onlinestream.EpisodeDetails, server string) (*onlinestream.EpisodeServer, error) {
	return W.WFindEpisodeServer(episode, server)
}
func (W _github_com_5rahim_hibike_pkg_extension_onlinestream_Provider) FindEpisodes(id string) ([]*onlinestream.EpisodeDetails, error) {
	return W.WFindEpisodes(id)
}
func (W _github_com_5rahim_hibike_pkg_extension_onlinestream_Provider) GetSettings() onlinestream.Settings {
	return W.WGetSettings()
}
func (W _github_com_5rahim_hibike_pkg_extension_onlinestream_Provider) Search(opts onlinestream.SearchOptions) ([]*onlinestream.SearchResult, error) {
	return W.WSearch(opts)
}

// _github_com_5rahim_hibike_pkg_extension_onlinestream_VideoExtractor is an interface wrapper for VideoExtractor type
type _github_com_5rahim_hibike_pkg_extension_onlinestream_VideoExtractor struct {
	IValue   interface{}
	WExtract func(uri string) ([]*onlinestream.VideoSource, error)
}

func (W _github_com_5rahim_hibike_pkg_extension_onlinestream_VideoExtractor) Extract(uri string) ([]*onlinestream.VideoSource, error) {
	return W.WExtract(uri)
}
