// Code generated by 'yaegi extract github.com/5rahim/hibike/pkg/extension/download'. DO NOT EDIT.

package yaegi_interp

import (
	"github.com/5rahim/hibike/pkg/extension/download"
	"reflect"
)

func init() {
	Symbols["github.com/5rahim/hibike/pkg/extension/download/download"] = map[string]reflect.Value{
		// type definitions
		"AnimeItem":     reflect.ValueOf((*download.AnimeItem)(nil)),
		"AnimeProvider": reflect.ValueOf((*download.AnimeProvider)(nil)),

		// interface wrapper definitions
		"_AnimeProvider": reflect.ValueOf((*_github_com_5rahim_hibike_pkg_extension_download_AnimeProvider)(nil)),
	}
}

// _github_com_5rahim_hibike_pkg_extension_download_AnimeProvider is an interface wrapper for AnimeProvider type
type _github_com_5rahim_hibike_pkg_extension_download_AnimeProvider struct {
	IValue          interface{}
	WDownload       func(item download.AnimeItem, headers map[string]string) error
	WGetItem        func(id string) (*download.AnimeItem, error)
	WInitUserConfig func(settings map[string]interface{})
	WSearch         func(query string) ([]*download.AnimeItem, error)
}

func (W _github_com_5rahim_hibike_pkg_extension_download_AnimeProvider) Download(item download.AnimeItem, headers map[string]string) error {
	return W.WDownload(item, headers)
}
func (W _github_com_5rahim_hibike_pkg_extension_download_AnimeProvider) GetItem(id string) (*download.AnimeItem, error) {
	return W.WGetItem(id)
}
func (W _github_com_5rahim_hibike_pkg_extension_download_AnimeProvider) InitUserConfig(settings map[string]interface{}) {
	W.WInitUserConfig(settings)
}
func (W _github_com_5rahim_hibike_pkg_extension_download_AnimeProvider) Search(query string) ([]*download.AnimeItem, error) {
	return W.WSearch(query)
}
