// Code generated by 'yaegi extract github.com/5rahim/hibike/pkg/util/bypass'. DO NOT EDIT.

package yaegi_interp

import (
	"github.com/5rahim/hibike/pkg/util/bypass"
	"reflect"
)

func init() {
	Symbols["github.com/5rahim/hibike/pkg/util/bypass/bypass"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddCloudFlareByPass": reflect.ValueOf(bypass.AddCloudFlareByPass),

		// type definitions
		"Options": reflect.ValueOf((*bypass.Options)(nil)),
	}
}
