// Code generated by 'yaegi extract github.com/5rahim/hibike/pkg/util/common'. DO NOT EDIT.

package yaegi_interp

import (
	"github.com/5rahim/hibike/pkg/util/common"
	"reflect"
)

func init() {
	Symbols["github.com/5rahim/hibike/pkg/util/common/common"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Reverse": reflect.ValueOf(common.Reverse),
	}
}
