// Code generated by 'yaegi extract github.com/5rahim/hibike/pkg/util/media'. DO NOT EDIT.

package yaegi_interp

import (
	"github.com/5rahim/hibike/pkg/util/media"
	"reflect"
)

func init() {
	Symbols["github.com/5rahim/hibike/pkg/util/media/media"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"IsValidVideoExtension": reflect.ValueOf(media.IsValidVideoExtension),
	}
}
