// Code generated by 'yaegi extract github.com/samber/lo'. DO NOT EDIT.

package yaegi_interp

import (
	"github.com/samber/lo"
	"reflect"
)

func init() {
	Symbols["github.com/samber/lo/lo"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AllCharset":              reflect.ValueOf(&lo.AllCharset).Elem(),
		"AlphanumericCharset":     reflect.ValueOf(&lo.AlphanumericCharset).Elem(),
		"Async0":                  reflect.ValueOf(lo.Async0),
		"Attempt":                 reflect.ValueOf(lo.Attempt),
		"AttemptWhile":            reflect.ValueOf(lo.AttemptWhile),
		"AttemptWhileWithDelay":   reflect.ValueOf(lo.AttemptWhileWithDelay),
		"AttemptWithDelay":        reflect.ValueOf(lo.AttemptWithDelay),
		"IsNil":                   reflect.ValueOf(lo.IsNil),
		"LettersCharset":          reflect.ValueOf(&lo.LettersCharset).Elem(),
		"LowerCaseLettersCharset": reflect.ValueOf(&lo.LowerCaseLettersCharset).Elem(),
		"Must0":                   reflect.ValueOf(lo.Must0),
		"NewDebounce":             reflect.ValueOf(lo.NewDebounce),
		"NumbersCharset":          reflect.ValueOf(&lo.NumbersCharset).Elem(),
		"RandomString":            reflect.ValueOf(lo.RandomString),
		"Range":                   reflect.ValueOf(lo.Range),
		"RuneLength":              reflect.ValueOf(lo.RuneLength),
		"SpecialCharset":          reflect.ValueOf(&lo.SpecialCharset).Elem(),
		"SynchronizeLocal":        reflect.ValueOf(lo.Synchronize),
		"Try":                     reflect.ValueOf(lo.Try),
		"Try0":                    reflect.ValueOf(lo.Try0),
		"Try1":                    reflect.ValueOf(lo.Try1),
		"TryCatch":                reflect.ValueOf(lo.TryCatch),
		"TryCatchWithErrorValue":  reflect.ValueOf(lo.TryCatchWithErrorValue),
		"TryWithErrorValue":       reflect.ValueOf(lo.TryWithErrorValue),
		"UpperCaseLettersCharset": reflect.ValueOf(&lo.UpperCaseLettersCharset).Elem(),
		"Validate":                reflect.ValueOf(lo.Validate),
	}
}
