// Code generated by 'yaegi extract github.com/EDDYCJY/fake-useragent'. DO NOT EDIT.

package yaegi_interp

import (
	"github.com/EDDYCJY/fake-useragent"
	"reflect"
)

func init() {
	Symbols["github.com/EDDYCJY/fake-useragent/browser"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Android":          reflect.ValueOf(browser.Android),
		"Chrome":           reflect.ValueOf(browser.Chrome),
		"Computer":         reflect.ValueOf(browser.Computer),
		"Firefox":          reflect.ValueOf(browser.Firefox),
		"IOS":              reflect.ValueOf(browser.IOS),
		"IPad":             reflect.ValueOf(browser.IPad),
		"IPhone":           reflect.ValueOf(browser.IPhone),
		"InternetExplorer": reflect.ValueOf(browser.InternetExplorer),
		"Linux":            reflect.ValueOf(browser.Linux),
		"MacOSX":           reflect.ValueOf(browser.MacOSX),
		"Mobile":           reflect.ValueOf(browser.Mobile),
		"NewBrowser":       reflect.ValueOf(browser.NewBrowser),
		"Random":           reflect.ValueOf(browser.Random),
		"Safari":           reflect.ValueOf(browser.Safari),

		// type definitions
		"Cache":  reflect.ValueOf((*browser.Cache)(nil)),
		"Client": reflect.ValueOf((*browser.Client)(nil)),
	}
}
