// Code generated by 'yaegi extract github.com/5rahim/hibike/pkg/extension/onlinestream'. DO NOT EDIT.

package yaegi_interp

import (
	"github.com/5rahim/hibike/pkg/extension/onlinestream"
	"reflect"
)

func init() {
	Symbols["github.com/5rahim/hibike/pkg/extension/onlinestream/onlinestream"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dub":             reflect.ValueOf(onlinestream.Dub),
		"Sub":             reflect.ValueOf(onlinestream.Sub),
		"SubAndDub":       reflect.ValueOf(onlinestream.SubAndDub),
		"VideoSourceDash": reflect.ValueOf(onlinestream.VideoSourceDash),
		"VideoSourceM3U8": reflect.ValueOf(onlinestream.VideoSourceM3U8),
		"VideoSourceMP4":  reflect.ValueOf(onlinestream.VideoSourceMP4),

		// type definitions
		"EpisodeDetails":  reflect.ValueOf((*onlinestream.EpisodeDetails)(nil)),
		"EpisodeServer":   reflect.ValueOf((*onlinestream.EpisodeServer)(nil)),
		"Provider":        reflect.ValueOf((*onlinestream.Provider)(nil)),
		"SearchResult":    reflect.ValueOf((*onlinestream.SearchResult)(nil)),
		"SubOrDub":        reflect.ValueOf((*onlinestream.SubOrDub)(nil)),
		"VideoExtractor":  reflect.ValueOf((*onlinestream.VideoExtractor)(nil)),
		"VideoSource":     reflect.ValueOf((*onlinestream.VideoSource)(nil)),
		"VideoSourceType": reflect.ValueOf((*onlinestream.VideoSourceType)(nil)),
		"VideoSubtitle":   reflect.ValueOf((*onlinestream.VideoSubtitle)(nil)),

		// interface wrapper definitions
		"_Provider":       reflect.ValueOf((*_github_com_5rahim_hibike_pkg_extension_onlinestream_Provider)(nil)),
		"_VideoExtractor": reflect.ValueOf((*_github_com_5rahim_hibike_pkg_extension_onlinestream_VideoExtractor)(nil)),
	}
}

// _github_com_5rahim_hibike_pkg_extension_onlinestream_Provider is an interface wrapper for Provider type
type _github_com_5rahim_hibike_pkg_extension_onlinestream_Provider struct {
	IValue             interface{}
	WFindEpisode       func(id string) ([]*onlinestream.EpisodeDetails, error)
	WFindEpisodeServer func(episode *onlinestream.EpisodeDetails, server string) (*onlinestream.EpisodeServer, error)
	WGetEpisodeServers func() []string
	WSearch            func(query string, dub bool) ([]*onlinestream.SearchResult, error)
}

func (W _github_com_5rahim_hibike_pkg_extension_onlinestream_Provider) FindEpisode(id string) ([]*onlinestream.EpisodeDetails, error) {
	return W.WFindEpisode(id)
}
func (W _github_com_5rahim_hibike_pkg_extension_onlinestream_Provider) FindEpisodeServer(episode *onlinestream.EpisodeDetails, server string) (*onlinestream.EpisodeServer, error) {
	return W.WFindEpisodeServer(episode, server)
}
func (W _github_com_5rahim_hibike_pkg_extension_onlinestream_Provider) GetEpisodeServers() []string {
	return W.WGetEpisodeServers()
}
func (W _github_com_5rahim_hibike_pkg_extension_onlinestream_Provider) Search(query string, dub bool) ([]*onlinestream.SearchResult, error) {
	return W.WSearch(query, dub)
}

// _github_com_5rahim_hibike_pkg_extension_onlinestream_VideoExtractor is an interface wrapper for VideoExtractor type
type _github_com_5rahim_hibike_pkg_extension_onlinestream_VideoExtractor struct {
	IValue   interface{}
	WExtract func(uri string) ([]*onlinestream.VideoSource, error)
}

func (W _github_com_5rahim_hibike_pkg_extension_onlinestream_VideoExtractor) Extract(uri string) ([]*onlinestream.VideoSource, error) {
	return W.WExtract(uri)
}
