// Code generated by 'yaegi extract github.com/PuerkitoBio/goquery'. DO NOT EDIT.

package yaegi_interp

import (
	"github.com/PuerkitoBio/goquery"
	"golang.org/x/net/html"
	"reflect"
)

func init() {
	Symbols["github.com/PuerkitoBio/goquery/goquery"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CloneDocument":           reflect.ValueOf(goquery.CloneDocument),
		"NewDocument":             reflect.ValueOf(goquery.NewDocument),
		"NewDocumentFromNode":     reflect.ValueOf(goquery.NewDocumentFromNode),
		"NewDocumentFromReader":   reflect.ValueOf(goquery.NewDocumentFromReader),
		"NewDocumentFromResponse": reflect.ValueOf(goquery.NewDocumentFromResponse),
		"NodeName":                reflect.ValueOf(goquery.NodeName),
		"OuterHtml":               reflect.ValueOf(goquery.OuterHtml),
		"Render":                  reflect.ValueOf(goquery.Render),
		"Single":                  reflect.ValueOf(goquery.Single),
		"SingleMatcher":           reflect.ValueOf(goquery.SingleMatcher),
		"ToEnd":                   reflect.ValueOf(goquery.ToEnd),

		// type definitions
		"Document":  reflect.ValueOf((*goquery.Document)(nil)),
		"Matcher":   reflect.ValueOf((*goquery.Matcher)(nil)),
		"Selection": reflect.ValueOf((*goquery.Selection)(nil)),

		// interface wrapper definitions
		"_Matcher": reflect.ValueOf((*_github_com_PuerkitoBio_goquery_Matcher)(nil)),
	}
}

// _github_com_PuerkitoBio_goquery_Matcher is an interface wrapper for Matcher type
type _github_com_PuerkitoBio_goquery_Matcher struct {
	IValue    interface{}
	WFilter   func(a0 []*html.Node) []*html.Node
	WMatch    func(a0 *html.Node) bool
	WMatchAll func(a0 *html.Node) []*html.Node
}

func (W _github_com_PuerkitoBio_goquery_Matcher) Filter(a0 []*html.Node) []*html.Node {
	return W.WFilter(a0)
}
func (W _github_com_PuerkitoBio_goquery_Matcher) Match(a0 *html.Node) bool {
	return W.WMatch(a0)
}
func (W _github_com_PuerkitoBio_goquery_Matcher) MatchAll(a0 *html.Node) []*html.Node {
	return W.WMatchAll(a0)
}
