// Code generated by 'yaegi extract github.com/5rahim/hibike/pkg/util/similarity'. DO NOT EDIT.

package yaegi_interp

import (
	"github.com/5rahim/hibike/pkg/util/similarity"
	"reflect"
)

func init() {
	Symbols["github.com/5rahim/hibike/pkg/util/similarity/similarity"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CompareWithLevenstein":         reflect.ValueOf(similarity.CompareWithLevenstein),
		"CompareWithSorensenDice":       reflect.ValueOf(similarity.CompareWithSorensenDice),
		"EliminateLeastSimilarValue":    reflect.ValueOf(similarity.EliminateLeastSimilarValue),
		"FindBestMatchWithLevenstein":   reflect.ValueOf(similarity.FindBestMatchWithLevenstein),
		"FindBestMatchWithSorensenDice": reflect.ValueOf(similarity.FindBestMatchWithSorensenDice),

		// type definitions
		"LevenshteinResult":  reflect.ValueOf((*similarity.LevenshteinResult)(nil)),
		"SorensenDiceResult": reflect.ValueOf((*similarity.SorensenDiceResult)(nil)),
	}
}
