// Code generated by 'yaegi extract github.com/5rahim/hibike/pkg/util/filtering'. DO NOT EDIT.

package yaegi_interp

import (
	"github.com/5rahim/hibike/pkg/util/filtering"
	"reflect"
)

func init() {
	Symbols["github.com/5rahim/hibike/pkg/util/filtering/filtering"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ExtractResolutionInt":         reflect.ValueOf(filtering.ExtractResolutionInt),
		"ExtractSeasonNumber":          reflect.ValueOf(filtering.ExtractSeasonNumber),
		"ValueContainsBatchKeywords":   reflect.ValueOf(filtering.ValueContainsBatchKeywords),
		"ValueContainsIgnoredKeywords": reflect.ValueOf(filtering.ValueContainsIgnoredKeywords),
		"ValueContainsNC":              reflect.ValueOf(filtering.ValueContainsNC),
		"ValueContainsSeason":          reflect.ValueOf(filtering.ValueContainsSeason),
		"ValueContainsSpecial":         reflect.ValueOf(filtering.ValueContainsSpecial),
	}
}
