name: Bug report
description: Report a bug you encountered
title: 'bug: '
labels:
  - bug
body:
  - type: checkboxes
    id: '1'
    attributes:
      label: Checklist
      description: Please follow the general troubleshooting steps first
      options:
        - label: >-
            My version of the app is the latest available
          required: true
        - label: >-
            I have checked open and closed [issues](https://github.com/5rahim/seanime/issues)
          required: true
        - label: >-
            I have checked the [docs](https://seanime.rahim.app/docs/faq) for a fix
          required: true
  - type: dropdown
    id: '2'
    attributes:
      label: Bug Severity
      description: Select the severity of the bug. Anything below "Panic" means the app doesn't crash.
      options:
        - Not sure
        - Panic / Crash
        - Usability is affected
        - Low
    validations:
      required: true
  - type: dropdown
    id: '3'
    attributes:
      label: Bug Area
      description: Select the general area of the app or process during which the bug occurred.
      options:
        - Other
        - Authentication
        - Configuration
        - Anime Library
        - Transcoding / Media Streaming
        - Torrent Streaming
        - Online Streaming
        - Manga
        - Settings
        - Offline mode
        - AniList
        - UI / Web Interface
    validations:
      required: true
  - type: textarea
    id: '4'
    attributes:
      label: Bug Description / Steps to Reproduce
      description: Precisely describe the bug you encountered and the steps to reproduce it. Avoid vague descriptions.
    validations:
      required: true
  - type: textarea
    id: '5'
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
  - type: textarea
    id: '6'
    attributes:
      label: Screenshots
      description: If applicable, add screenshots of the bug
  - type: textarea
    id: '7'
    attributes:
      label: Logs
      description: If applicable, add terminal output, browser console logs or stack traces. You can use [pastebin](https://pastebin.com) to share large logs.
    validations:
      required: true
  - type: checkboxes
    id: '8'
    attributes:
      label: Debugging Checklist
      description: Confirm you have included at least some of the following debugging information. If you haven't, please do so before submitting the issue.
      options:
        - label: >-
            I have included error messages
          required: false
        - label: >-
            I have included terminal output
          required: false
        - label: >-
            I have included browser console logs
          required: false
  - type: input
    id: '9'
    attributes:
      label: App Version
      description: Enter the version of Seanime you are using.
      placeholder: v1.0.0
    validations:
      required: true
  - type: dropdown
    id: '10'
    attributes:
      label: Operating System
      options:
        - Windows
        - Linux
        - MacOS
    validations:
      required: true
