export const enum WSEvents {
    SCAN_PROGRESS = "scan-progress",
    SCAN_STATUS = "scan-status",
    REFRESHED_ANILIST_COLLECTION = "refreshed-anilist-collection",
    REFRESHED_ANILIST_MANGA_COLLECTION = "refreshed-anilist-manga-collection",
    LIBRARY_WATCHER_FILE_ADDED = "library-watcher-file-added",
    LIBRARY_WATCHER_FILE_REMOVED = "library-watcher-file-removed",
    AUTO_DOWNLOADER_ITEM_ADDED = "auto-downloader-item-added",
    AUTO_SCAN_STARTED = "auto-scan-started",
    AUTO_SCAN_COMPLETED = "auto-scan-completed",
    PLAYBACK_MANAGER_PROGRESS_TRACKING_STARTED = "playback-manager-progress-tracking-started",
    PLAYBACK_MANAGER_PROGRESS_TRACKING_STOPPED = "playback-manager-progress-tracking-stopped",
    PLAYBACK_MANAGER_PROGRESS_VIDEO_COMPLETED = "playback-manager-progress-video-completed",
    PLAYBACK_MANAGER_PROGRESS_PLAYBACK_STATE = "playback-manager-progress-playback-state",
    PLAYBACK_MANAGER_PROGRESS_UPDATED = "playback-manager-progress-updated",
    PLAYBACK_MANAGER_PLAYLIST_STATE = "playback-manager-playlist-state",
    ERROR_TOAST = "error-toast",
    SUCCESS_TOAST = "success-toast",
    INFO_TOAST = "info-toast",
    WARNING_TOAST = "warning-toast",
    REFRESHED_MANGA_DOWNLOAD_DATA = "refreshed-manga-download-data",
    CHAPTER_DOWNLOAD_QUEUE_UPDATED = "chapter-download-queue-updated",
    OFFLINE_SNAPSHOT_CREATED = "offline-snapshot-created",
    MEDIASTREAM_SHUTDOWN_STREAM = "mediastream-shutdown-stream",
}
