name: Publish Release Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Release tag to build (e.g., v2.8.5)"
        required: true

jobs:
  build-and-push-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get release version
        id: get_version
        run: |
          VERSION=${{ github.event.release.tag_name || github.event.inputs.version }}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Convert owner to lowercase
        id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: builder-release
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ steps.get_version.outputs.version }}
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}/seanime:latest
            ghcr.io/${{ steps.string.outputs.lowercase }}/seanime:${{ steps.get_version.outputs.version }}
