name: Build Development Docker Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      clear_cache:
        description: "Clear build cache before running"
        required: false
        type: boolean
        default: false

jobs:
  build-and-push-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert owner to lowercase
        id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define cache scope
        id: cache_scope
        run: |
          if [[ "${{ github.event.inputs.clear_cache }}" == "true" ]]; then
            echo "scope=${{ github.workflow }}-${{ github.ref_name }}-${{ github.run_id }}" >> $GITHUB_OUTPUT
          else
            echo "scope=${{ github.workflow }}-${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production-cpu-from-source
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}/seanime:development
            ghcr.io/${{ steps.string.outputs.lowercase }}/seanime:dev-${{ github.sha }}
          cache-from: type=gha,scope=dev-cpu
          cache-to: type=gha,scope=dev-cpu,mode=max
