name: Release Draft

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  create-release-draft:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      #      - name: Login to Docker Hub
      #        uses: docker/login-action@v1
      #        with:
      #          username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      #
      #      - name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Generate Release Notes
        run: python ./.github/scripts/generate-release-notes.py


      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --release-notes whats-new.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}